name: Checkmarx One Scan
on:
  workflow_dispatch:
  
jobs:
  checkmarx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: hb0730/maven-action@v1.0.2
        with:
          maven-version: 3.14.0

      - name: Download Cx SCA Resolver
        run: |
          mkdir -p sca-resolver; cd sca-resolver
          curl -L -o ScaResolver-linux64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xvzf ScaResolver-linux64.tar.gz

      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: ${{ secrets.CX_TENANT_NAME }}
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          branch: ${{ github.ref }}
          additional_params: '--sca-resolver ./sca-resolver/ScaResolver'